page_1:
 - "§e-- §bHelp page 1 of 6 | Type /help 2 for second page §e--"
 - "§e/tell <player> <message> §a= §bPrivate Message a player."
 - "§e/op <player> §a= §bGive a player Operator Permissions."
 - "§e/kick <player> [reason] §a= §bKick a player with an optional reason."
 - "§e/ban <player> [reason] §a= §bBans a player with an optional reason."
 - "§e/ban-ip <player> [reason] §a= §bIP Bans a player with an optional reason."
 - "§e/banlist [ips] §a= §bDisplays a list of all (IP) banned players."
 - "§e/reload §a= §bReloads all server and plugin config files."
page_2:
 - "§e-- §bHelp page 2 of 6 | Type /help 3 for third page §e--"
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
page_3:
 - "§e-- §bHelp page 3 of 6 | Type /help 4 for fourth page §e--"
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
page_4:
 - "§e-- §bHelp page 4 of 6 | Type /help 5 for fifth page §e--"
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
page_5:
 - "§e-- §bHelp page 5 of 6 | Type /help 6 for sixth page §e--"
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
page_6:
 - "§e-- §bHelp page 6 of 6 §e--"
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
 - ""
