page_1:
  message_1: "§e-- §bHelp page 1 of 5 | Type /help 2 for second page §e--"
  message_2: "§e/tell <player> <message> §a= §bPrivate Message a player."
  message_3: "§e/op <player> §a= §bGive a player Operator Permissions."
  message_4: "§e/kick <player> [reason] §a= §bKick a player with an optional reason."
  message_5: "§e/ban <player> [reason] §a= §bBans a player with an optional reason."
  message_6: "§e/ban-ip <player> [reason] §a= §bIP Bans a player with an optional reason."
  message_7: "§e/banlist [ips] §a= §bDisplays a list of all (IP) banned players."
  message_8: "§e/reload §a= §bReloads all server and plugin config files."
page_2:
  message_1: "§e-- §bHelp page 2 of 5 | Type /help 3 for third page §e--"
  message_2: ""
  message_3: ""
  message_4: ""
  message_5: ""
  message_6: ""
  message_7: ""
  message_8: ""
page_3:
  message_1: "§e-- §bHelp page 3 of 5 | Type /help 4 for fourth page §e--"
  message_2: ""
  message_3: ""
  message_4: ""
  message_5: ""
  message_6: ""
  message_7: ""
  message_8: ""
page_4:
  message_1: "§e-- §bHelp page 4 of 5 | Type /help 5 for fifth page §e--"
  message_2: ""
  message_3: ""
  message_4: ""
  message_5: ""
  message_6: ""
  message_7: ""
  message_8: ""
page_5:
  message_1: "§e-- §bHelp page 5 of 6 | Type /help 6 for sixth page §e--"
  message_2: ""
  message_3: ""
  message_4: ""
  message_5: ""
  message_6: ""
  message_7: ""
  message_8: ""
page_6:
  message_1: "§e-- §bHelp page 6 of 6 §e--"
  message_2: ""
  message_3: ""
  message_4: ""
  message_5: ""
  message_6: ""
  message_7: ""
  message_8: ""
